project:
  type: website
  output-dir: docs/

website:
  title: "Rick's Portfolio"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Career"
        href: career.qmd
      - text: "Projects"
        href: projects_corrected.qmd
      - text: "Achievements"
        href: achievements.qmd
      - text: "Contact"
        href: contact.qmd
      # Maybe add a blog tab as well, that'd be fun

format:
  html:
    anchor-sections: false
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

include-after-body: www/lightbox-scripts.html
